<?php
	$rP = $this->ee->libGetResPath("devguard","http");
?>
<!-- QOX DEVGUARD FLOATING LOCK .: START :. -->
<div onMouseOver="ee7_dg_op_1()" title="Click here to close QOX ExEngine DevGuard session." 
onMouseOut="ee7_dg_op_alpha()" onClick="ee7_dg_op_m_click()" id="ee7_dg_div" class="warp" 
style="position: fixed;width: 50px;height: 50px; background-color: #C1A080; bottom: 10px; right: 12px; opacity: 0.25; cursor: pointer;">
	<div class="lock" style="background-image: url(<?php echo $rP; ?>lock.png); background-repeat: no-repeat;background-size: 30px 30px;width: 100%;height: 100%; margin:9px 15px 15px 10px; opacity: 0.5">
	</div>
</div>
<script type="text/javascript">
	function ee7_dg_op_1(){
		document.getElementById("ee7_dg_div").style.opacity = 1;
	}
	function ee7_dg_op_alpha(){
		document.getElementById("ee7_dg_div").style.opacity = 0.25;
	}
	function ee7_dg_op_m_click(){
		var url = document.URL;
		if(url.indexOf("?")==-1){
			window.location = url + "?close_guard";
		}else{
			window.location = url + "&close_guard";
		}
	}
</script>
<!-- QOX DEVGUARD FLOATING LOCK .: END :. -->