<?php
	$rP = $this->ee->libGetResPath("devguard","http");
	/*
	<div onMouseOver="caca()" title="Click to close ExEngine DevGuard session." 
onMouseOut="coco()" onClick="cucu()" id="coqui" class="warp" 
style="border-radius: 0px 15px 15px 15px;position: fixed;width: 50px;height: 50px;border: solid 3px grey;background-color: #000;bottom: 10px;right: 12px; opacity: 0.4; cursor: pointer;">
	<div class="lock" style="background-image: url(<?php echo $rP; ?>lock.png); background-repeat: no-repeat;background-size: 30px 30px;width: 100%;height: 100%; margin:8px 15px 15px 10px; opacity: 0.8">
	</div>
</div>
<script type="text/javascript">
	function caca(){
		document.getElementById("coqui").style.opacity = 0.9;
	}
	function coco(){
		document.getElementById("coqui").style.opacity = 0.4;
	}
	function cucu(){
		var url = document.URL;
		if(url.indexOf("?")==-1){
			window.location = url + "?close_guard";
		}else{
			window.location = url + "&close_guard";
		}
	}
</script>
*/
?><!-- ExEngine DevGuard START -->
<div onMouseOver="caca()" title="Click to close ExEngine DevGuard session." onMouseOut="coco()" onClick="cucu()" id="coqui" class="warp" style="border-radius: 0px 15px 15px 15px;position: fixed;width: 50px;height: 50px;border: solid 3px grey;background-color: #000;bottom: 10px;right: 12px; opacity: 0.4; cursor: pointer;"><div class="lock" style="background-image: url(<?php echo $rP; ?>lock.png); background-repeat: no-repeat;background-size: 30px 30px;width: 100%;height: 100%; margin:8px 15px 15px 10px; opacity: 0.8"></div></div><script type="text/javascript">function caca(){document.getElementById("coqui").style.opacity = 0.9;}function coco(){document.getElementById("coqui").style.opacity = 0.4;}function cucu(){var url = document.URL;if(url.indexOf("?")==-1){window.location = url + "?close_guard";}else{window.location = url + "&close_guard";}}</script>
<!-- ExEngine DevGuard END -->
