<?php
	$httpP = $this->
ee->libGetResPath("devguard","http");
	$logoEE = $this->ee->miscGetResPath("http")."dev_guard_shield.png";
?>
<html>
<head>
	<title>Application protected by QOX ExEngine DevGuard</title>
	<link href='http://fonts.googleapis.com/css?family=Alegreya+Sans:100,400,500,700,800,900' rel='stylesheet' type='text/css'>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<style>
	body {	
		margin: 0px;
		font-size: 16px;
		font-family: 'Alegreya Sans', sans-serif;			
		background-color: #333;
		background-image: url(<?php print $this->ee->miscGetResPath("http"); ?>big_bg_qox.png);
		background-position: 0% 0%;
		background-repeat: no-repeat;		
	}
	#container {
		display: table;
		width: 100%;
		height: 100%;
	}
	#cont2 {
		display: table-cell;
		vertical-align: middle;
	}
	.ee_btn {
		text-transform: uppercase;
		border: 0px;
		background-color: #333;
		color: #B8B8B8;
		font-weight: 100;
		padding: 9px;
		font-size: 12px;
		letter-spacing: 3px;
	}
	#home {
		text-align: left;
		padding: 25px;
		width: 50%;
		margin: 20px auto 20px auto;
		box-shadow: 2px 2px 9px rgba(0, 0, 0, 0.2);
		font-weight: 400;
		border: 1px solid #DCC9B6;
		background: #c1a080;
		background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2MxYTA4MCIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNjZWI1OWIiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
		background: -moz-linear-gradient(left,  #c1a080 0%, #ceb59b 100%);
		background: -webkit-gradient(linear, left top, right top, color-stop(0%,#c1a080), color-stop(100%,#ceb59b));
		background: -webkit-linear-gradient(left,  #c1a080 0%,#ceb59b 100%);
		background: -o-linear-gradient(left,  #c1a080 0%,#ceb59b 100%);
		background: -ms-linear-gradient(left,  #c1a080 0%,#ceb59b 100%);
		background: linear-gradient(to right,  #c1a080 0%,#ceb59b 100%);
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#c1a080', endColorstr='#ceb59b',GradientType=1 );
	}
</style>
<script type='text/javascript'>
	window.onload=function(){
		document.getElementById("upload_file").onchange = function() {
		    document.getElementById("devguard_form").submit();
		}
	}
</script>
</head>
<body>
	<div id="container">
		<div id="cont2">
			<div id="home">
				<form id="devguard_form" action="<?php echo $_SERVER["REQUEST_URI"]; ?>" method="post" enctype="multipart/form-data">
				<div align="center"><img src="<?php echo $logoEE; ?>" /></div>
				<p>
					This application is in <span style="font-weight: 500;">development stage</span> and its access is restricted to select users, if you need access contact application developers to get a copy of the key file.
				</p>
				<?php if ($invalid_key) { ?>
				<p style="color: rgb(194, 0, 0); text-align: center; font-weight: 500;">
					<?php echo $invalid_key; ?></p>
				<?php } ?>
				<p style="text-align: center; font-weight: 500;">
					Please select the project key to start a session<br/>
					<input type="file" name="upload_file" id="upload_file"><br/>
					<input class="ee_btn" type="submit" value="Authenticate">
				</p>
				<p style="text-align: center;">
					<img src="<?php print $this->ee->miscGetResPath("http"); ?>ee7_powered_line.png" />
				</p>
			</form>
		</div>
	</div>
</div>
</body>
</html>