<?php
$ee = &ee_gi();
$jq = new jquery($ee);
$httpCommonPath = $ee->miscGetResPath("http");
$httpResPath = $ee->libGetResPath('bootstrap','http');
$httpResPathFA = $ee->libGetResPath('fontawesome','http');
$httpResPathFonts = $ee->libGetResPath('fonts','http');
?>
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><?php print $DG_L["gateway_title"]; ?></title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="ExEngine Error Message">
	<meta name="author" content="QOX Corporation">
	<link href="<?php print $httpResPath; ?>themes/bootstrap.flatly.min.css" rel="stylesheet">
	<link href="<?php print $httpResPathFA; ?>css/font-awesome.min.css" rel="stylesheet">
	<script>
		window.onload=function(){
			document.getElementById("upload_file").onchange = function() {
				document.getElementById("devguard_form").submit();
			}
		}
	</script>
	<style>
		@font-face {
			font-family: 'ethno_q';
			src: url('<?php print $httpResPathFonts; ?>ethnocentric.otf');
		}
		@font-face {
			font-family: 'ethno';
			src: url('<?php print $httpResPathFonts; ?>ethnocentric_italic.otf');
		}
		.QLogo {
			font-family: ethno_q;
			background-color: #000;
			color: #D96D00;
			padding-right: 4px;
			padding-left: 4px;
			font-size: 1.4em;
		}
		.EELogo {
			font-family: ethno;
			font-size: 1.4em;
		}
		.navbar-brand:hover {
			color: #FFF !important;
		}
	</style>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand">
				<!--<img src="<?php print $httpCommonPath; ?>qox_q.png" style="max-height: 32px; margin-top: -6px;" title="QOX Corporation">-->
				<span class="QLogo">QOX</span>
				&nbsp;
				<span class="EELogo">ExEngine</span>
			</a>
		</div>
	</div>
</div>
<div class="container-fluid" style="margin-top: 80px;">
	<div class="panel panel-warning">
		<div class="panel-heading">
			<?php print $DG_L["gateway_title"]; ?>
		</div>
		<div class="panel-body">
			<form id="devguard_form" class="form form-horizontal" action="<?php echo $_SERVER["REQUEST_URI"]; ?>" method="post" enctype="multipart/form-data">
				<p>
					<?php print $DG_L["welcome_text"]; ?>
				</p>
				<?php if ($invalid_key) { ?>
					<p style="color: rgb(194, 0, 0); font-weight: 500;">
						<?php echo $invalid_key; ?></p>
				<?php } ?>
				<p style="font-weight: 500;">
					<?php print $DG_L["select_key"]; ?><br><br>
					<input type="file" name="upload_file" id="upload_file"><br>
					<input class="btn btn-default" type="submit" value="<?php print $DG_L["auth_button"]; ?>">
				</p>
			</form>
		</div>
	</div>

</div>
<div class="container-fluid">
	<p><small>&copy <?php print strftime('%Y');?> <a href="//qox-corp.com" target="_blank">QOX Corporation</a></small></p>
</div>

<?php $jq->load(); ?>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<script src="<?php print $httpResPath; ?>basic/js/bootstrap.min.js"></script>
<script src="<?php print $httpResPath; ?>plugins/holder/docs.min.js"></script>
</body>

</html>