<form class="form-horizontal" method="post" action="?F=new_controller_act">
    <fieldset>

        <!-- Form Name -->
        <legend>New Controller</legend>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-3 control-label" for="name">Name</label>
            <div class="col-md-6">
                <input id="name" name="name" type="text" placeholder="class name" class="form-control " required="required">

            </div>
        </div>

        <!-- Button -->
        <div class="form-group">
            <label class="col-md-3 control-label" for=""></label>
            <div class="col-lg-6">
                <button id="" name="" class="btn btn-primary">Create Controller</button>
            </div>
        </div>

    </fieldset>
</form>
