<form class="form-horizontal" method="post" action="?F=new_controller_act">
    <fieldset>

        <!-- Form Name -->


        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-3 control-label" for="name">Name</label>
            <div class="col-md-6">
                <input id="name" name="name" type="text" placeholder="class name" class="form-control " required="required">

            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label" for="checkboxes">Source options</label>
            <div class="col-lg-6">
                <div class="checkbox">
                    <label for="checkboxes-0">
                        <input type="checkbox" name="commented" id="checkboxes-0" value="true">
                        Commented
                    </label>
                </div>

                <div class="checkbox">
                    <label for="checkboxes-1">
                        <input type="checkbox" name="defaults" id="checkboxes-1" value="true">
                        Defaults set
                    </label>
                </div>

            </div>

        <!-- Button -->
        <div class="form-group">
            <label class="col-md-3 control-label" for=""></label>
            <div class="col-lg-6">
                <button id="" name="" class="btn btn-primary">Create Controller</button>
            </div>
        </div>

    </fieldset>
</form>
