<?php
$ee = &ee_gi();
$jq = new jquery($ee);
$httpCommonPath = $ee->miscGetResPath("http");
$httpResPath = $ee->libGetResPath('bootstrap','http');
$httpResPathFA = $ee->libGetResPath('fontawesome','http');
$httpResPathFonts = $ee->libGetResPath('fonts','http');
?>
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>QOX ExEngine Error : <?php print $title; ?></title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="ExEngine Error Message">
	<meta name="author" content="QOX Corporation">
	<link href="<?php print $httpResPath; ?>themes/bootstrap.flatly.min.css" rel="stylesheet">
	<link href="<?php print $httpResPathFA; ?>css/font-awesome.min.css" rel="stylesheet">

	<style>
	@font-face {
		font-family: 'ethno';
		src: url('<?php print $httpResPathFonts; ?>ethnocentric_italic.otf');
	}
	@font-face {
		font-family: 'ethno_n';
		src: url('<?php print $httpResPathFonts; ?>ethnocentric.otf');
	}
	.EELogo {
		font-family: ethno;
	}
	.QLogo {
		font-family: ethno_n;
	}
	.navbar-brand:hover {
		color: #FFF !important;
	}
	</style>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand">
				<img src="<?php print $httpCommonPath; ?>qox_q.png" style="max-height: 32px; margin-top: -6px;" title="QOX Corporation">&nbsp;
				<span class="EELogo">ExEngine</span>
			</a>
		</div>
		<div class="navbar-collapse collapse">
		</div>
	</div>
</div>
<div class="container-fluid" style="margin-top: 80px;">
	<div class="panel panel-danger">
		<div class="panel-heading">
			Error : <?php print $title; ?>
		</div>
		<div class="panel-body">
		<p style="font-weight: bold"><?php print $mess; ?></p>
		<p><?php print $haltinfo; ?></p>
		</div>
	</div>

</div>
<div class="container-fluid">
	<p><small>&copy <?php print strftime('%Y');?> <a href="//qox-corp.com" target="_blank">QOX Corporation</a></small></p>
</div>

<?php $jq->load(); ?>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<script src="<?php print $httpResPath; ?>basic/js/bootstrap.min.js"></script>
<script src="<?php print $httpResPath; ?>plugins/holder/docs.min.js"></script>
</body>

</html>